### ISSUE TITLE
chapter 3 그래들로 자바 프로젝트 만들기

### ISSUE THREAD

**Issue by Pyohwan** [thecodinglive/hanbit-gradle-book-example#1]
소스 코드는 없나요?

**Comment by sjyun** [comment]
아직 챕터 변경을 반영을 못했습니다
주말에 챕터를 변경해서 맞춰놓도록 하겠습니다

감사합니당

https://github.com/thecodinglive/hanbit-gradle-book-example/tree/master/ch02/ch02-java

**Comment by sjyun** [comment]
변경을 완료하였습니다.
감사합니다.
https://github.com/thecodinglive/hanbit-gradle-book-example/tree/master/ch03/ch03-java
